-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "text" text NOT NULL, "status" character varying NOT NULL DEFAULT 'IN_PROGRESS', "priority" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "todo_user" table
CREATE TABLE "todo_user" ("todo_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("todo_id", "user_id"), CONSTRAINT "todo_user_todo_id" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "todo_user_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
